import { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-toolbox";
import "@nomicfoundation/hardhat-ethers";
import * as fs from "fs";
import * as path from "path";

// Deployer key resolution order:
//   1. BESU_DEPLOYER_KEY env var (set by deploy scripts; required for CI/prod)
//   2. ../keys/admin/admin-1.key (auto-generated by scripts/02-generate-node-keys.sh)
//   3. undefined — networks that need a signer will fail loudly with a clear message
function loadBesuDeployerKey(): string | undefined {
  if (process.env.BESU_DEPLOYER_KEY) {
    const k = process.env.BESU_DEPLOYER_KEY;
    return k.startsWith("0x") ? k : `0x${k}`;
  }
  const keyPath = path.resolve(__dirname, "..", "keys", "admin", "admin-1.key");
  if (fs.existsSync(keyPath)) {
    const raw = fs.readFileSync(keyPath, "utf8").trim();
    return raw.startsWith("0x") ? raw : `0x${raw}`;
  }
  return undefined;
}

const besuDeployerKey = loadBesuDeployerKey();
const besuAccounts = besuDeployerKey ? [besuDeployerKey] : [];

const config: HardhatUserConfig = {
  solidity: "0.8.24",
  networks: {
    sepolia: {
      url: "https://ethereum-sepolia-rpc.publicnode.com",
      accounts: process.env.PRIVATE_KEY ? [process.env.PRIVATE_KEY] : [],
      timeout: 60000,
    },
    besu: {
      url: "https://besu.essi.studio",
      chainId: 1947,
      accounts: besuAccounts,
      timeout: 60000,
      gasPrice: 0,
    },
    "besu-local": {
      url: process.env.BESU_LOCAL_RPC_URL || "http://localhost:8545",
      chainId: 1947,
      accounts: besuAccounts,
      timeout: 60000,
      gasPrice: 0,
    },
  },
  etherscan: {
    apiKey: {
      sepolia: process.env.ETHERSCAN_API_KEY || "",
      mainnet: process.env.ETHERSCAN_API_KEY || "",
    },
    customChains: [
      {
        network: "sepolia",
        chainId: 11155111,
        urls: {
          apiURL: "https://api-sepolia.etherscan.io/api",
          browserURL: "https://sepolia.etherscan.io",
        },
      },
    ],
  },
  mocha: {
    timeout: 100000,
  },
};

export default config;
