# Besu Network Permissioning Configuration
# This file controls who can deploy smart contracts on the network

# Accounts allowed to deploy smart contracts
# Anyone can send transactions, but only these accounts can deploy contracts
accounts-allowlist = [
"0x639028b24c7707cbdf1a7c328c159d1254bc1fa2",
 "0x2649130e09e6927a2e8fac6bc81c40d7964447e6",
 "0xaf8809cc23dad34d08c0747801529dfb8b2d82b6"
]

# Node permissioning (optional - can restrict which nodes can join)
# nodes-allowlist = []
